// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fstiffo/pills/ent/activeingredient"
	"fstiffo/pills/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActiveIngredientDelete is the builder for deleting a ActiveIngredient entity.
type ActiveIngredientDelete struct {
	config
	hooks    []Hook
	mutation *ActiveIngredientMutation
}

// Where appends a list predicates to the ActiveIngredientDelete builder.
func (aid *ActiveIngredientDelete) Where(ps ...predicate.ActiveIngredient) *ActiveIngredientDelete {
	aid.mutation.Where(ps...)
	return aid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aid *ActiveIngredientDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, aid.sqlExec, aid.mutation, aid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (aid *ActiveIngredientDelete) ExecX(ctx context.Context) int {
	n, err := aid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aid *ActiveIngredientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(activeingredient.Table, sqlgraph.NewFieldSpec(activeingredient.FieldID, field.TypeInt))
	if ps := aid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, aid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	aid.mutation.done = true
	return affected, err
}

// ActiveIngredientDeleteOne is the builder for deleting a single ActiveIngredient entity.
type ActiveIngredientDeleteOne struct {
	aid *ActiveIngredientDelete
}

// Where appends a list predicates to the ActiveIngredientDelete builder.
func (aido *ActiveIngredientDeleteOne) Where(ps ...predicate.ActiveIngredient) *ActiveIngredientDeleteOne {
	aido.aid.mutation.Where(ps...)
	return aido
}

// Exec executes the deletion query.
func (aido *ActiveIngredientDeleteOne) Exec(ctx context.Context) error {
	n, err := aido.aid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{activeingredient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aido *ActiveIngredientDeleteOne) ExecX(ctx context.Context) {
	if err := aido.Exec(ctx); err != nil {
		panic(err)
	}
}
