// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"fstiffo/pills/ent/purchase"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PurchaseCreate is the builder for creating a Purchase entity.
type PurchaseCreate struct {
	config
	mutation *PurchaseMutation
	hooks    []Hook
}

// SetPuchasedAt sets the "puchased_at" field.
func (pc *PurchaseCreate) SetPuchasedAt(t time.Time) *PurchaseCreate {
	pc.mutation.SetPuchasedAt(t)
	return pc
}

// SetQuantity sets the "quantity" field.
func (pc *PurchaseCreate) SetQuantity(i int) *PurchaseCreate {
	pc.mutation.SetQuantity(i)
	return pc
}

// Mutation returns the PurchaseMutation object of the builder.
func (pc *PurchaseCreate) Mutation() *PurchaseMutation {
	return pc.mutation
}

// Save creates the Purchase in the database.
func (pc *PurchaseCreate) Save(ctx context.Context) (*Purchase, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PurchaseCreate) SaveX(ctx context.Context) *Purchase {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PurchaseCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PurchaseCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PurchaseCreate) check() error {
	if _, ok := pc.mutation.PuchasedAt(); !ok {
		return &ValidationError{Name: "puchased_at", err: errors.New(`ent: missing required field "Purchase.puchased_at"`)}
	}
	if _, ok := pc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Purchase.quantity"`)}
	}
	if v, ok := pc.mutation.Quantity(); ok {
		if err := purchase.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Purchase.quantity": %w`, err)}
		}
	}
	return nil
}

func (pc *PurchaseCreate) sqlSave(ctx context.Context) (*Purchase, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PurchaseCreate) createSpec() (*Purchase, *sqlgraph.CreateSpec) {
	var (
		_node = &Purchase{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(purchase.Table, sqlgraph.NewFieldSpec(purchase.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.PuchasedAt(); ok {
		_spec.SetField(purchase.FieldPuchasedAt, field.TypeTime, value)
		_node.PuchasedAt = value
	}
	if value, ok := pc.mutation.Quantity(); ok {
		_spec.SetField(purchase.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	return _node, _spec
}

// PurchaseCreateBulk is the builder for creating many Purchase entities in bulk.
type PurchaseCreateBulk struct {
	config
	err      error
	builders []*PurchaseCreate
}

// Save creates the Purchase entities in the database.
func (pcb *PurchaseCreateBulk) Save(ctx context.Context) ([]*Purchase, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Purchase, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PurchaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PurchaseCreateBulk) SaveX(ctx context.Context) []*Purchase {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PurchaseCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PurchaseCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
