// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"fstiffo/pills/ent/predicate"
	"fstiffo/pills/ent/purchase"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PurchaseUpdate is the builder for updating Purchase entities.
type PurchaseUpdate struct {
	config
	hooks    []Hook
	mutation *PurchaseMutation
}

// Where appends a list predicates to the PurchaseUpdate builder.
func (pu *PurchaseUpdate) Where(ps ...predicate.Purchase) *PurchaseUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetPuchasedAt sets the "puchased_at" field.
func (pu *PurchaseUpdate) SetPuchasedAt(t time.Time) *PurchaseUpdate {
	pu.mutation.SetPuchasedAt(t)
	return pu
}

// SetNillablePuchasedAt sets the "puchased_at" field if the given value is not nil.
func (pu *PurchaseUpdate) SetNillablePuchasedAt(t *time.Time) *PurchaseUpdate {
	if t != nil {
		pu.SetPuchasedAt(*t)
	}
	return pu
}

// SetQuantity sets the "quantity" field.
func (pu *PurchaseUpdate) SetQuantity(i int) *PurchaseUpdate {
	pu.mutation.ResetQuantity()
	pu.mutation.SetQuantity(i)
	return pu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (pu *PurchaseUpdate) SetNillableQuantity(i *int) *PurchaseUpdate {
	if i != nil {
		pu.SetQuantity(*i)
	}
	return pu
}

// AddQuantity adds i to the "quantity" field.
func (pu *PurchaseUpdate) AddQuantity(i int) *PurchaseUpdate {
	pu.mutation.AddQuantity(i)
	return pu
}

// Mutation returns the PurchaseMutation object of the builder.
func (pu *PurchaseUpdate) Mutation() *PurchaseMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PurchaseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PurchaseUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PurchaseUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PurchaseUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PurchaseUpdate) check() error {
	if v, ok := pu.mutation.Quantity(); ok {
		if err := purchase.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Purchase.quantity": %w`, err)}
		}
	}
	return nil
}

func (pu *PurchaseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(purchase.Table, purchase.Columns, sqlgraph.NewFieldSpec(purchase.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.PuchasedAt(); ok {
		_spec.SetField(purchase.FieldPuchasedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Quantity(); ok {
		_spec.SetField(purchase.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedQuantity(); ok {
		_spec.AddField(purchase.FieldQuantity, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{purchase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PurchaseUpdateOne is the builder for updating a single Purchase entity.
type PurchaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PurchaseMutation
}

// SetPuchasedAt sets the "puchased_at" field.
func (puo *PurchaseUpdateOne) SetPuchasedAt(t time.Time) *PurchaseUpdateOne {
	puo.mutation.SetPuchasedAt(t)
	return puo
}

// SetNillablePuchasedAt sets the "puchased_at" field if the given value is not nil.
func (puo *PurchaseUpdateOne) SetNillablePuchasedAt(t *time.Time) *PurchaseUpdateOne {
	if t != nil {
		puo.SetPuchasedAt(*t)
	}
	return puo
}

// SetQuantity sets the "quantity" field.
func (puo *PurchaseUpdateOne) SetQuantity(i int) *PurchaseUpdateOne {
	puo.mutation.ResetQuantity()
	puo.mutation.SetQuantity(i)
	return puo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (puo *PurchaseUpdateOne) SetNillableQuantity(i *int) *PurchaseUpdateOne {
	if i != nil {
		puo.SetQuantity(*i)
	}
	return puo
}

// AddQuantity adds i to the "quantity" field.
func (puo *PurchaseUpdateOne) AddQuantity(i int) *PurchaseUpdateOne {
	puo.mutation.AddQuantity(i)
	return puo
}

// Mutation returns the PurchaseMutation object of the builder.
func (puo *PurchaseUpdateOne) Mutation() *PurchaseMutation {
	return puo.mutation
}

// Where appends a list predicates to the PurchaseUpdate builder.
func (puo *PurchaseUpdateOne) Where(ps ...predicate.Purchase) *PurchaseUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PurchaseUpdateOne) Select(field string, fields ...string) *PurchaseUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Purchase entity.
func (puo *PurchaseUpdateOne) Save(ctx context.Context) (*Purchase, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PurchaseUpdateOne) SaveX(ctx context.Context) *Purchase {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PurchaseUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PurchaseUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PurchaseUpdateOne) check() error {
	if v, ok := puo.mutation.Quantity(); ok {
		if err := purchase.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Purchase.quantity": %w`, err)}
		}
	}
	return nil
}

func (puo *PurchaseUpdateOne) sqlSave(ctx context.Context) (_node *Purchase, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(purchase.Table, purchase.Columns, sqlgraph.NewFieldSpec(purchase.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Purchase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, purchase.FieldID)
		for _, f := range fields {
			if !purchase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != purchase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.PuchasedAt(); ok {
		_spec.SetField(purchase.FieldPuchasedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Quantity(); ok {
		_spec.SetField(purchase.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedQuantity(); ok {
		_spec.AddField(purchase.FieldQuantity, field.TypeInt, value)
	}
	_node = &Purchase{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{purchase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
