// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"fstiffo/pills/ent/activeingredient"
	"fstiffo/pills/ent/medicine"
	"fstiffo/pills/ent/predicate"
	"fstiffo/pills/ent/stockinglog"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StockingLogQuery is the builder for querying StockingLog entities.
type StockingLogQuery struct {
	config
	ctx                  *QueryContext
	order                []stockinglog.OrderOption
	inters               []Interceptor
	predicates           []predicate.StockingLog
	withMedicine         *MedicineQuery
	withActiveIngredient *ActiveIngredientQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StockingLogQuery builder.
func (slq *StockingLogQuery) Where(ps ...predicate.StockingLog) *StockingLogQuery {
	slq.predicates = append(slq.predicates, ps...)
	return slq
}

// Limit the number of records to be returned by this query.
func (slq *StockingLogQuery) Limit(limit int) *StockingLogQuery {
	slq.ctx.Limit = &limit
	return slq
}

// Offset to start from.
func (slq *StockingLogQuery) Offset(offset int) *StockingLogQuery {
	slq.ctx.Offset = &offset
	return slq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (slq *StockingLogQuery) Unique(unique bool) *StockingLogQuery {
	slq.ctx.Unique = &unique
	return slq
}

// Order specifies how the records should be ordered.
func (slq *StockingLogQuery) Order(o ...stockinglog.OrderOption) *StockingLogQuery {
	slq.order = append(slq.order, o...)
	return slq
}

// QueryMedicine chains the current query on the "medicine" edge.
func (slq *StockingLogQuery) QueryMedicine() *MedicineQuery {
	query := (&MedicineClient{config: slq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := slq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stockinglog.Table, stockinglog.FieldID, selector),
			sqlgraph.To(medicine.Table, medicine.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stockinglog.MedicineTable, stockinglog.MedicineColumn),
		)
		fromU = sqlgraph.SetNeighbors(slq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryActiveIngredient chains the current query on the "active_ingredient" edge.
func (slq *StockingLogQuery) QueryActiveIngredient() *ActiveIngredientQuery {
	query := (&ActiveIngredientClient{config: slq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := slq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stockinglog.Table, stockinglog.FieldID, selector),
			sqlgraph.To(activeingredient.Table, activeingredient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stockinglog.ActiveIngredientTable, stockinglog.ActiveIngredientColumn),
		)
		fromU = sqlgraph.SetNeighbors(slq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StockingLog entity from the query.
// Returns a *NotFoundError when no StockingLog was found.
func (slq *StockingLogQuery) First(ctx context.Context) (*StockingLog, error) {
	nodes, err := slq.Limit(1).All(setContextOp(ctx, slq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stockinglog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (slq *StockingLogQuery) FirstX(ctx context.Context) *StockingLog {
	node, err := slq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StockingLog ID from the query.
// Returns a *NotFoundError when no StockingLog ID was found.
func (slq *StockingLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(1).IDs(setContextOp(ctx, slq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stockinglog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (slq *StockingLogQuery) FirstIDX(ctx context.Context) int {
	id, err := slq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StockingLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StockingLog entity is found.
// Returns a *NotFoundError when no StockingLog entities are found.
func (slq *StockingLogQuery) Only(ctx context.Context) (*StockingLog, error) {
	nodes, err := slq.Limit(2).All(setContextOp(ctx, slq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stockinglog.Label}
	default:
		return nil, &NotSingularError{stockinglog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (slq *StockingLogQuery) OnlyX(ctx context.Context) *StockingLog {
	node, err := slq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StockingLog ID in the query.
// Returns a *NotSingularError when more than one StockingLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (slq *StockingLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(2).IDs(setContextOp(ctx, slq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stockinglog.Label}
	default:
		err = &NotSingularError{stockinglog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (slq *StockingLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := slq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StockingLogs.
func (slq *StockingLogQuery) All(ctx context.Context) ([]*StockingLog, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryAll)
	if err := slq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StockingLog, *StockingLogQuery]()
	return withInterceptors[[]*StockingLog](ctx, slq, qr, slq.inters)
}

// AllX is like All, but panics if an error occurs.
func (slq *StockingLogQuery) AllX(ctx context.Context) []*StockingLog {
	nodes, err := slq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StockingLog IDs.
func (slq *StockingLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if slq.ctx.Unique == nil && slq.path != nil {
		slq.Unique(true)
	}
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryIDs)
	if err = slq.Select(stockinglog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (slq *StockingLogQuery) IDsX(ctx context.Context) []int {
	ids, err := slq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (slq *StockingLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryCount)
	if err := slq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, slq, querierCount[*StockingLogQuery](), slq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (slq *StockingLogQuery) CountX(ctx context.Context) int {
	count, err := slq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (slq *StockingLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryExist)
	switch _, err := slq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (slq *StockingLogQuery) ExistX(ctx context.Context) bool {
	exist, err := slq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StockingLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (slq *StockingLogQuery) Clone() *StockingLogQuery {
	if slq == nil {
		return nil
	}
	return &StockingLogQuery{
		config:               slq.config,
		ctx:                  slq.ctx.Clone(),
		order:                append([]stockinglog.OrderOption{}, slq.order...),
		inters:               append([]Interceptor{}, slq.inters...),
		predicates:           append([]predicate.StockingLog{}, slq.predicates...),
		withMedicine:         slq.withMedicine.Clone(),
		withActiveIngredient: slq.withActiveIngredient.Clone(),
		// clone intermediate query.
		sql:  slq.sql.Clone(),
		path: slq.path,
	}
}

// WithMedicine tells the query-builder to eager-load the nodes that are connected to
// the "medicine" edge. The optional arguments are used to configure the query builder of the edge.
func (slq *StockingLogQuery) WithMedicine(opts ...func(*MedicineQuery)) *StockingLogQuery {
	query := (&MedicineClient{config: slq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	slq.withMedicine = query
	return slq
}

// WithActiveIngredient tells the query-builder to eager-load the nodes that are connected to
// the "active_ingredient" edge. The optional arguments are used to configure the query builder of the edge.
func (slq *StockingLogQuery) WithActiveIngredient(opts ...func(*ActiveIngredientQuery)) *StockingLogQuery {
	query := (&ActiveIngredientClient{config: slq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	slq.withActiveIngredient = query
	return slq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StockedAt time.Time `json:"stocked_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StockingLog.Query().
//		GroupBy(stockinglog.FieldStockedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (slq *StockingLogQuery) GroupBy(field string, fields ...string) *StockingLogGroupBy {
	slq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StockingLogGroupBy{build: slq}
	grbuild.flds = &slq.ctx.Fields
	grbuild.label = stockinglog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StockedAt time.Time `json:"stocked_at,omitempty"`
//	}
//
//	client.StockingLog.Query().
//		Select(stockinglog.FieldStockedAt).
//		Scan(ctx, &v)
func (slq *StockingLogQuery) Select(fields ...string) *StockingLogSelect {
	slq.ctx.Fields = append(slq.ctx.Fields, fields...)
	sbuild := &StockingLogSelect{StockingLogQuery: slq}
	sbuild.label = stockinglog.Label
	sbuild.flds, sbuild.scan = &slq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StockingLogSelect configured with the given aggregations.
func (slq *StockingLogQuery) Aggregate(fns ...AggregateFunc) *StockingLogSelect {
	return slq.Select().Aggregate(fns...)
}

func (slq *StockingLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range slq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, slq); err != nil {
				return err
			}
		}
	}
	for _, f := range slq.ctx.Fields {
		if !stockinglog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if slq.path != nil {
		prev, err := slq.path(ctx)
		if err != nil {
			return err
		}
		slq.sql = prev
	}
	return nil
}

func (slq *StockingLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StockingLog, error) {
	var (
		nodes       = []*StockingLog{}
		withFKs     = slq.withFKs
		_spec       = slq.querySpec()
		loadedTypes = [2]bool{
			slq.withMedicine != nil,
			slq.withActiveIngredient != nil,
		}
	)
	if slq.withMedicine != nil || slq.withActiveIngredient != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, stockinglog.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StockingLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StockingLog{config: slq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, slq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := slq.withMedicine; query != nil {
		if err := slq.loadMedicine(ctx, query, nodes, nil,
			func(n *StockingLog, e *Medicine) { n.Edges.Medicine = e }); err != nil {
			return nil, err
		}
	}
	if query := slq.withActiveIngredient; query != nil {
		if err := slq.loadActiveIngredient(ctx, query, nodes, nil,
			func(n *StockingLog, e *ActiveIngredient) { n.Edges.ActiveIngredient = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (slq *StockingLogQuery) loadMedicine(ctx context.Context, query *MedicineQuery, nodes []*StockingLog, init func(*StockingLog), assign func(*StockingLog, *Medicine)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*StockingLog)
	for i := range nodes {
		if nodes[i].medicine_stocking_logs == nil {
			continue
		}
		fk := *nodes[i].medicine_stocking_logs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(medicine.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "medicine_stocking_logs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (slq *StockingLogQuery) loadActiveIngredient(ctx context.Context, query *ActiveIngredientQuery, nodes []*StockingLog, init func(*StockingLog), assign func(*StockingLog, *ActiveIngredient)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*StockingLog)
	for i := range nodes {
		if nodes[i].active_ingredient_stocking_logs == nil {
			continue
		}
		fk := *nodes[i].active_ingredient_stocking_logs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(activeingredient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "active_ingredient_stocking_logs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (slq *StockingLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := slq.querySpec()
	_spec.Node.Columns = slq.ctx.Fields
	if len(slq.ctx.Fields) > 0 {
		_spec.Unique = slq.ctx.Unique != nil && *slq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, slq.driver, _spec)
}

func (slq *StockingLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stockinglog.Table, stockinglog.Columns, sqlgraph.NewFieldSpec(stockinglog.FieldID, field.TypeInt))
	_spec.From = slq.sql
	if unique := slq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if slq.path != nil {
		_spec.Unique = true
	}
	if fields := slq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stockinglog.FieldID)
		for i := range fields {
			if fields[i] != stockinglog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := slq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := slq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := slq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := slq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (slq *StockingLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(slq.driver.Dialect())
	t1 := builder.Table(stockinglog.Table)
	columns := slq.ctx.Fields
	if len(columns) == 0 {
		columns = stockinglog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if slq.sql != nil {
		selector = slq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if slq.ctx.Unique != nil && *slq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range slq.predicates {
		p(selector)
	}
	for _, p := range slq.order {
		p(selector)
	}
	if offset := slq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := slq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StockingLogGroupBy is the group-by builder for StockingLog entities.
type StockingLogGroupBy struct {
	selector
	build *StockingLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (slgb *StockingLogGroupBy) Aggregate(fns ...AggregateFunc) *StockingLogGroupBy {
	slgb.fns = append(slgb.fns, fns...)
	return slgb
}

// Scan applies the selector query and scans the result into the given value.
func (slgb *StockingLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, slgb.build.ctx, ent.OpQueryGroupBy)
	if err := slgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockingLogQuery, *StockingLogGroupBy](ctx, slgb.build, slgb, slgb.build.inters, v)
}

func (slgb *StockingLogGroupBy) sqlScan(ctx context.Context, root *StockingLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(slgb.fns))
	for _, fn := range slgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*slgb.flds)+len(slgb.fns))
		for _, f := range *slgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*slgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := slgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StockingLogSelect is the builder for selecting fields of StockingLog entities.
type StockingLogSelect struct {
	*StockingLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sls *StockingLogSelect) Aggregate(fns ...AggregateFunc) *StockingLogSelect {
	sls.fns = append(sls.fns, fns...)
	return sls
}

// Scan applies the selector query and scans the result into the given value.
func (sls *StockingLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sls.ctx, ent.OpQuerySelect)
	if err := sls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockingLogQuery, *StockingLogSelect](ctx, sls.StockingLogQuery, sls, sls.inters, v)
}

func (sls *StockingLogSelect) sqlScan(ctx context.Context, root *StockingLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sls.fns))
	for _, fn := range sls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
