// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fstiffo/pills/ent/predicate"
	"fstiffo/pills/ent/stockinglog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StockingLogDelete is the builder for deleting a StockingLog entity.
type StockingLogDelete struct {
	config
	hooks    []Hook
	mutation *StockingLogMutation
}

// Where appends a list predicates to the StockingLogDelete builder.
func (sld *StockingLogDelete) Where(ps ...predicate.StockingLog) *StockingLogDelete {
	sld.mutation.Where(ps...)
	return sld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sld *StockingLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sld.sqlExec, sld.mutation, sld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sld *StockingLogDelete) ExecX(ctx context.Context) int {
	n, err := sld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sld *StockingLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(stockinglog.Table, sqlgraph.NewFieldSpec(stockinglog.FieldID, field.TypeInt))
	if ps := sld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sld.mutation.done = true
	return affected, err
}

// StockingLogDeleteOne is the builder for deleting a single StockingLog entity.
type StockingLogDeleteOne struct {
	sld *StockingLogDelete
}

// Where appends a list predicates to the StockingLogDelete builder.
func (sldo *StockingLogDeleteOne) Where(ps ...predicate.StockingLog) *StockingLogDeleteOne {
	sldo.sld.mutation.Where(ps...)
	return sldo
}

// Exec executes the deletion query.
func (sldo *StockingLogDeleteOne) Exec(ctx context.Context) error {
	n, err := sldo.sld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{stockinglog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sldo *StockingLogDeleteOne) ExecX(ctx context.Context) {
	if err := sldo.Exec(ctx); err != nil {
		panic(err)
	}
}
