// Code generated by ent, DO NOT EDIT.

package stockinglog

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the stockinglog type in the database.
	Label = "stocking_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStockedAt holds the string denoting the stocked_at field in the database.
	FieldStockedAt = "stocked_at"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// EdgeMedicine holds the string denoting the medicine edge name in mutations.
	EdgeMedicine = "medicine"
	// Table holds the table name of the stockinglog in the database.
	Table = "stocking_logs"
	// MedicineTable is the table that holds the medicine relation/edge.
	MedicineTable = "stocking_logs"
	// MedicineInverseTable is the table name for the Medicine entity.
	// It exists in this package in order to avoid circular dependency with the "medicine" package.
	MedicineInverseTable = "medicines"
	// MedicineColumn is the table column denoting the medicine relation/edge.
	MedicineColumn = "medicine_stocking_logs"
)

// Columns holds all SQL columns for stockinglog fields.
var Columns = []string{
	FieldID,
	FieldStockedAt,
	FieldQuantity,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "stocking_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"medicine_stocking_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
)

// OrderOption defines the ordering options for the StockingLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStockedAt orders the results by the stocked_at field.
func ByStockedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStockedAt, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByMedicineField orders the results by medicine field.
func ByMedicineField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMedicineStep(), sql.OrderByField(field, opts...))
	}
}
func newMedicineStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MedicineInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MedicineTable, MedicineColumn),
	)
}
