// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ActiveIngredient is the predicate function for activeingredient builders.
type ActiveIngredient func(*sql.Selector)

// ConsumptionLog is the predicate function for consumptionlog builders.
type ConsumptionLog func(*sql.Selector)

// Medicine is the predicate function for medicine builders.
type Medicine func(*sql.Selector)

// Prescription is the predicate function for prescription builders.
type Prescription func(*sql.Selector)

// StockingLog is the predicate function for stockinglog builders.
type StockingLog func(*sql.Selector)
